"""add_user_preferences

Revision ID: 95306c0f05e4
Revises: d0e85591057e
Create Date: 2026-02-05 09:50:25.231329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95306c0f05e4'
down_revision: Union[str, Sequence[str], None] = 'd0e85591057e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('theme', sa.String(), nullable=True))
    op.add_column('users', sa.Column('privacy_dm', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'privacy_dm')
    op.drop_column('users', 'theme')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
