"""add reply_to_id to direct_messages

Revision ID: d3bd85e4fd25
Revises: 4312a74d6f66
Create Date: 2026-02-12 21:31:10.659319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3bd85e4fd25'
down_revision: Union[str, Sequence[str], None] = '4312a74d6f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_messages', sa.Column('reply_to_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'direct_messages', 'direct_messages', ['reply_to_id'], ['id'], ondelete='SET NULL')
    op.add_column('messages', sa.Column('reply_to_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'reply_to_id')
    op.drop_constraint(None, 'direct_messages', type_='foreignkey')
    op.drop_column('direct_messages', 'reply_to_id')
    # ### end Alembic commands ###
