"""add_user_notification_settings

Revision ID: e69a5eb5cd24
Revises: 95306c0f05e4
Create Date: 2026-02-05 09:56:28.192259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69a5eb5cd24'
down_revision: Union[str, Sequence[str], None] = '95306c0f05e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notif_friend_requests', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notif_direct_messages', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notif_mentions', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notif_mentions')
    op.drop_column('users', 'notif_direct_messages')
    op.drop_column('users', 'notif_friend_requests')
    # ### end Alembic commands ###
