"""add_attachments_and_edited_flag

Revision ID: e966364f74a1
Revises: e69a5eb5cd24
Create Date: 2026-02-05 10:16:37.360099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e966364f74a1'
down_revision: Union[str, Sequence[str], None] = 'e69a5eb5cd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_messages', sa.Column('attachments', sa.Text(), nullable=True))
    op.add_column('direct_messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    op.add_column('direct_messages', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('attachments', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'attachments')
    op.drop_column('direct_messages', 'updated_at')
    op.drop_column('direct_messages', 'is_edited')
    op.drop_column('direct_messages', 'attachments')
    # ### end Alembic commands ###
