"""add_server_roles_members

Revision ID: f8a9b8a6a7ac
Revises: 6f86433d607f
Create Date: 2026-02-05 13:03:45.576910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a9b8a6a7ac'
down_revision: Union[str, Sequence[str], None] = '6f86433d607f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('joined_at', sa.String(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=True),
    sa.Column('muted_until', sa.String(), nullable=True),
    sa.Column('is_deafened', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('permissions', sa.BigInteger(), nullable=True),
    sa.Column('is_hoisted', sa.Boolean(), nullable=True),
    sa.Column('position', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_role_association',
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['server_members.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['server_roles.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_role_association')
    op.drop_table('server_roles')
    op.drop_table('server_members')
    # ### end Alembic commands ###
